[package]
name = "mythos"
description = "AI 驱动的剧情跑团桌面应用"
version.workspace = true
edition.workspace = true

[lib]
name = "mythos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde.workspace = true
serde_json = "1"
tauri.workspace = true
mythos-store.workspace = true

[dev-dependencies]
rusqlite.workspace = true
